---
title: "lab 6"
output: pdf_document
date: "2023-02-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Normal Normal Conjugacy
The proof of Normal-Normal conjugacy is in chapter 5 of Bayes Rules book. They prove that the posterior distribution can be written in the form:
$$
p(\mu \mid y_{1},...,y_{n}) \sim N\left(\frac{\theta \sigma^2+n\bar{y}\tau^2}{n\tau^2+\sigma^2},\frac{\tau^2\sigma^2}{n\tau^2+\sigma^2} \right)
$$

With some rearranging we can also write it as:
$$
p(\mu \mid y_{1},...,y_{n}) \sim N\left(\frac{\frac{1}{\tau^2}\theta + \frac{n}{\sigma^2} \bar{y}}{\frac{1}{\tau^2}+\frac{n}{\sigma^2}}, \frac{1}{\frac{1}{\tau^2} + \frac{n}{\sigma^2}} \right)
$$

## Example
(Ex 5.11 from Bayes Rules)

Prof. Abebe and Prof. Morales both recently finished their PhDs and are teaching their first statistics classes at Bayesian University. Their colleagues told them that the average final exam score across all students, $\mu$, varies Normally from year to year with a mean of 80 points and a standard deviation of 4. Further, individual students’ scores Y vary Normally around $\mu$
with a known standard deviation of 3 points.
$$\mu \sim N(\theta = 80, \tau^2 = 4^2)$$
$$Y \sim N(\mu, \sigma^2 = 3^2)$$
\begin{enumerate}
  \item Prof. Abebe conducts the final exam and observes that his 32 students scored an average of 86 points. Calculate the posterior mean and variance of $\mu$ using the data from Prof. Abebe’s class.
$$
\begin{aligned}
p(\mu \mid y_{11},...,y_{1n_1}) &\sim N\left(\frac{\frac{1}{\tau^2}\theta + \frac{n_1}{\sigma_1^2} \bar{y_1}}{\frac{1}{\tau^2}+\frac{n_1}{\sigma_1^2}}, \frac{1}{\frac{1}{\tau^2} + \frac{n_1}{\sigma_1^2}} \right) \\
&\sim N\left(\frac{\frac{1}{4^2}*80 + \frac{32}{3^2} * 86}{\frac{1}{4^2}+\frac{32}{3^2}}, \frac{1}{\frac{1}{4^2} + \frac{32}{3^2}} \right) \\
&\sim N(85.8964, 0.2764)
\end{aligned}
$$
  \item Prof. Morales conducts the final exam and observes that her 32 students scored an average of 82 points. Calculate the posterior mean and variance of $\mu$ using the data from Prof. Morales’ class.
$$
\begin{aligned}
p(\mu \mid y_{21},...,y_{2n_2}) &\sim N\left(\frac{\frac{1}{\tau^2}\theta + \frac{n_2}{\sigma_2^2} \bar{y_2}}{\frac{1}{\tau^2}+\frac{n_2}{\sigma_2^2}}, \frac{1}{\frac{1}{\tau^2} + \frac{n_2}{\sigma_2^2}} \right) \\
&\sim N\left(\frac{\frac{1}{4^2}*80 + \frac{32}{3^2} * 82}{\frac{1}{4^2}+\frac{32}{3^2}}, \frac{1}{\frac{1}{4^2} + \frac{32}{3^2}} \right) \\
&\sim N(81.9655, 0.2764)
\end{aligned}
$$
  \item Next, use Prof. Abebe and Prof. Morales’ combined exams to calculate the posterior mean and variance of $\mu$.
$$
\begin{aligned}
p(\mu \mid y_{11},...,y_{1n_1}, y_{21},...,y_{2n_2}) &\sim N\left(\frac{\frac{1}{\tau^2}\theta + \frac{n}{\sigma^2} \bar{y}}{\frac{1}{\tau^2}+\frac{n}{\sigma^2}}, \frac{1}{\frac{1}{\tau^2} + \frac{n_1}{\sigma^2}} \right) \\
&\sim N\left(\frac{\frac{1}{4^2}*80 + \frac{32+32}{3^2} * \frac{\sum y_1 + \sum y_2}{32+32}}{\frac{1}{4^2}+\frac{32+32}{3^2}}, \frac{1}{\frac{1}{4^2} + \frac{32+32}{3^2}} \right) \\
&\sim N\left(\frac{\frac{1}{16}*80 + \frac{64}{9} * \frac{32\bar{y}_1 + 32\bar{y}_2}{64}}{\frac{1}{16}+\frac{64}{9}}, \frac{1}{\frac{1}{16} + \frac{64}{9}} \right) \\
&\sim N(83.9652, 0.1394)
\end{aligned}
$$
\end{enumerate}